modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="genshin_weapon"
version="1.0.3"
displayName="genshin_weapon"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://space.bilibili.com/290906342"
logoFile="logo.png"
authors="He_RT"
description='''
Ô­ÉñÎäÆ÷
'''

[[dependencies.genshin_weapon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




